name = input("请输入您的姓名")
print('*'*80)
age = int(input("请输入您的年龄"))
print('*'*80)
sexxy = input("请输入您的性别")
print('*'*80)
high = float(input("请输入身高"))
print('*'*80)
weight = float(input("请输入体重"))
print('*'*80)
ID_number = int(input("请输入您的身份证号码"))
print('*'*80)
education = input("请输入您的学历")
print('*'*80)
birthday = input("请输入您的出生年月")
print('*'*80)
amazy = input("请输入您老婆的名字")
print('*'*80)
addr = input("请输入你的家庭地址")
print('*'*80)
tel = int(input("请输入电话号码"))
print('*'*80)
case = input("请输入职位")
print('*'*80)
money = int(input("请输入薪水"))
print('*'*80)
print("姓名：%s\n 年龄：%d\n 性别：%s\n 身高：%.2f\n 体重：%.2f\n 身份证号码：%d\n 学历：%s\n 出生年月：%s\n 家属名字：%s\n 家庭地址:%s\n 电话号码：%d\n 职位：%s\n 薪水：%s\n"%(name,age,sexxy,high,weight,ID_number,education,birthday,amazy,addr,tel,case,money))
print('*'*80)
