print('*'*60)
name = input("请输入姓名")
print('*'*60)
gender = input("请输入性别")
print('*'*60)
phone = input("请输入电话号码")
print('*'*60)
addr = input("请输入家庭地址")
print('*'*60)
email = input("请输入邮箱号码")
print('*'*60)
print("姓名%s\n 性别%s\n 电话号码%s\n 家庭地址%s\n 邮箱号%s\n"%(name,gender,phone,addr,email))
