list = ["易县","上海","三亚","山东","青岛","哈尔滨","宁夏"]
print(list)
print(sorted(list))
print(list)
print(sorted(list,reverse=True))
print(list)
list.reverse()
print(list)
list.reverse()
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)
